### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by TWD** [nioc/xmpp-bot#17]
Hi, is it possible that the bot responds with an attachment instead of plain text?
Thanks

**Comment by nioc** [comment]
Hello.
I assume your mean send an attachment to XMPP chat/groupchat? Yes it may be possible.
But from what source: sent to webhook?

## Quick analysis

### Webhook

Need to handle file parsing and storage

### XMPP

Using HTTP upload ([XEP-0363](https://xmpp.org/extensions/xep-0363.html)), the workflow is the following:
- service discovery to server (send `iq` disco#items):
  - get upload service,
  - handle error
- service discovery request to upload service (send `iq` disco#info):
  - get max-file-size,
  - handle error
- reserve upload slot (send `iq`)
  - get url to used,
  - handle error (file too large, quota, ...)
- upload the file to the url slot (PUT HTTP)
  - if success: send XMPP message with link
  - else: handle error

It requires your XMPP server supports this XEP-0363.

## Conclusion

As it is a massive feature, I keep it open to see if others need it.

In the meantime, if you can handle it, please feel free to propose a pull request 😄
