### ISSUE TITLE
[Question] Timezone

### ISSUE THREAD

**Issue by roughnecks** [nioc/xmpp-bot#22]
Hello,

does the bot only work with UTC zone?
This is a webhook log for a webhook I ran at 10 AM CEST

`roughnecks [10/Nov/2024:09:19:55 +0000] "POST /webhooks/kuma HTTP/1.1" 200`

Thanks

**Comment by nioc** [comment]
The [Morgan logger](https://github.com/expressjs/morgan?tab=readme-ov-file#dateformat) use UTC only, yes.
